const wikiData = {
  sushicore: `
"<!DOCTYPE html>\n<html lang=\"vi\">\n<head>\n<meta charset=\"UTF-8\">\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n<title>SushiCore Wiki - SushiGangs</title>\n<link href=\"https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:wght@400;600;800&family=JetBrains+Mono&display=swap\" rel=\"stylesheet\">\n<link rel=\"stylesheet\" href=\"style.css\">\n<style>\n/* WIKI SPECIFIC STYLES */\n.wiki-main { padding: 100px 20px 40px; max-width: 900px; margin: 0 auto; width: 100%; color: #b8aece; line-height: 1.6; }\n.wiki-main h1 { font-size: 2.5rem; color: #fff; margin-bottom: 10px; }\n.wiki-main h2 { font-size: 1.8rem; color: #fff; margin-top: 40px; margin-bottom: 15px; padding-bottom: 10px; border-bottom: 1px solid rgba(255,255,255,0.1); }\n.wiki-main h3 { font-size: 1.3rem; color: #ff77aa; margin-top: 20px; margin-bottom: 10px; }\n.wiki-main p { margin-bottom: 15px; }\n.wiki-main ul, .wiki-main ol { margin-bottom: 15px; padding-left: 20px; }\n.wiki-main li { margin-bottom: 8px; }\n\n/* CODE BLOCKS */\n.code-wrapper { position: relative; margin-bottom: 20px; border-radius: 8px; overflow: hidden; background: rgba(15, 8, 32, 0.6); border: 1px solid rgba(255,255,255,0.1); backdrop-filter: blur(10px); }\n.code-header { display: flex; justify-content: space-between; align-items: center; padding: 8px 15px; background: rgba(0,0,0,0.3); font-family: 'JetBrains Mono', monospace; font-size: 0.85rem; color: #8a7da5; border-bottom: 1px solid rgba(255,255,255,0.05); }\n.copy-btn { background: none; border: none; color: #b8aece; cursor: pointer; transition: color 0.2s; display: flex; align-items: center; gap: 5px; font-size: 0.85rem; }\n.copy-btn:hover { color: #fff; }\n.code-wrapper pre { padding: 15px; overflow-x: auto; font-family: 'JetBrains Mono', monospace; font-size: 0.9rem; color: #e0d8f0; margin: 0; tab-size: 4; }\ncode { font-family: 'JetBrains Mono', monospace; background: rgba(255,255,255,0.1); padding: 2px 6px; border-radius: 4px; font-size: 0.9em; color: #ffaa77; }\n\n/* TABLE */\n.wiki-table-
<truncated 12479 bytes>
`,

  sushidecor: `
"<!DOCTYPE html>\n<html lang=\"vi\">\n<head>\n<meta charset=\"UTF-8\">\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n<title>SushiDecor Wiki - SushiGangs</title>\n<link href=\"https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:wght@400;600;800&family=JetBrains+Mono&display=swap\" rel=\"stylesheet\">\n<link rel=\"stylesheet\" href=\"style.css\">\n<style>\n/* WIKI SPECIFIC STYLES */\n.wiki-main { padding: 100px 20px 40px; max-width: 900px; margin: 0 auto; width: 100%; color: #b8aece; line-height: 1.6; }\n.wiki-main h1 { font-size: 2.5rem; color: #fff; margin-bottom: 10px; }\n.wiki-main h2 { font-size: 1.8rem; color: #fff; margin-top: 40px; margin-bottom: 15px; padding-bottom: 10px; border-bottom: 1px solid rgba(255,255,255,0.1); }\n.wiki-main h3 { font-size: 1.3rem; color: #ff77aa; margin-top: 20px; margin-bottom: 10px; }\n.wiki-main p { margin-bottom: 15px; }\n.wiki-main ul, .wiki-main ol { margin-bottom: 15px; padding-left: 20px; }\n.wiki-main li { margin-bottom: 8px; }\n\n/* CODE BLOCKS */\n.code-wrapper { position: relative; margin-bottom: 20px; border-radius: 8px; overflow: hidden; background: rgba(15, 8, 32, 0.6); border: 1px solid rgba(255,255,255,0.1); backdrop-filter: blur(10px); }\n.code-header { display: flex; justify-content: space-between; align-items: center; padding: 8px 15px; background: rgba(0,0,0,0.3); font-family: 'JetBrains Mono', monospace; font-size: 0.85rem; color: #8a7da5; border-bottom: 1px solid rgba(255,255,255,0.05); }\n.copy-btn { background: none; border: none; color: #b8aece; cursor: pointer; transition: color 0.2s; display: flex; align-items: center; gap: 5px; font-size: 0.85rem; }\n.copy-btn:hover { color: #fff; }\n.code-wrapper pre { padding: 15px; overflow-x: auto; font-family: 'JetBrains Mono', monospace; font-size: 0.9rem; color: #e0d8f0; margin: 0; tab-size: 4; }\ncode { font-family: 'JetBrains Mono', monospace; background: rgba(255,255,255,0.1); padding: 2px 6px; border-radius: 4px; font-size: 0.9em; color: #ffaa77; }\n\n/* TABLE */\n.wiki-table
<truncated 11102 bytes>
`,

  sushilove: `
"<!DOCTYPE html>\n<html lang=\"vi\">\n<head>\n<meta charset=\"UTF-8\">\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n<title>SushiLove Wiki - SushiGangs</title>\n<link href=\"https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:wght@400;600;800&family=JetBrains+Mono&display=swap\" rel=\"stylesheet\">\n<link rel=\"stylesheet\" href=\"style.css\">\n<style>\n.wiki-main { padding: 100px 20px 40px; max-width: 900px; margin: 0 auto; width: 100%; color: #b8aece; line-height: 1.6; }\n.wiki-main h1 { font-size: 2.5rem; color: #fff; margin-bottom: 10px; }\n.wiki-main h2 { font-size: 1.8rem; color: #fff; margin-top: 40px; margin-bottom: 15px; padding-bottom: 10px; border-bottom: 1px solid rgba(255,255,255,0.1); }\n.wiki-main h3 { font-size: 1.3rem; color: #ff77aa; margin-top: 20px; margin-bottom: 10px; }\n.wiki-main p { margin-bottom: 15px; }\n.wiki-main ul, .wiki-main ol { margin-bottom: 15px; padding-left: 20px; }\n.wiki-main li { margin-bottom: 8px; }\n\n.code-wrapper { position: relative; margin-bottom: 20px; border-radius: 8px; overflow: hidden; background: rgba(15, 8, 32, 0.6); border: 1px solid rgba(255,255,255,0.1); backdrop-filter: blur(10px); }\n.code-header { display: flex; justify-content: space-between; align-items: center; padding: 8px 15px; background: rgba(0,0,0,0.3); font-family: 'JetBrains Mono', monospace; font-size: 0.85rem; color: #8a7da5; border-bottom: 1px solid rgba(255,255,255,0.05); }\n.copy-btn { background: none; border: none; color: #b8aece; cursor: pointer; transition: color 0.2s; display: flex; align-items: center; gap: 5px; font-size: 0.85rem; }\n.copy-btn:hover { color: #fff; }\n.code-wrapper pre { padding: 15px; overflow-x: auto; font-family: 'JetBrains Mono', monospace; font-size: 0.9rem; color: #e0d8f0; margin: 0; tab-size: 4; }\ncode { font-family: 'JetBrains Mono', monospace; background: rgba(255,255,255,0.1); padding: 2px 6px; border-radius: 4px; font-size: 0.9em; color: #ffaa77; }\n\n.wiki-table-wrapper { overflow-x: auto; margin-bottom: 20px; border-radi
<truncated 8479 bytes>
`,

  sushimanager: `
"<!DOCTYPE html>\n<html lang=\"vi\">\n<head>\n<meta charset=\"UTF-8\">\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n<title>SushiManager Wiki - SushiGangs</title>\n<link href=\"https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:wght@400;600;800&family=JetBrains+Mono&display=swap\" rel=\"stylesheet\">\n<link rel=\"stylesheet\" href=\"style.css\">\n<style>\n.wiki-main { padding: 100px 20px 40px; max-width: 900px; margin: 0 auto; width: 100%; color: #b8aece; line-height: 1.6; }\n.wiki-main h1 { font-size: 2.5rem; color: #fff; margin-bottom: 10px; }\n.wiki-main h2 { font-size: 1.8rem; color: #fff; margin-top: 40px; margin-bottom: 15px; padding-bottom: 10px; border-bottom: 1px solid rgba(255,255,255,0.1); }\n.wiki-main h3 { font-size: 1.3rem; color: #ff77aa; margin-top: 20px; margin-bottom: 10px; }\n.wiki-main p { margin-bottom: 15px; }\n.wiki-main ul, .wiki-main ol { margin-bottom: 15px; padding-left: 20px; }\n.wiki-main li { margin-bottom: 8px; }\n\n.code-wrapper { position: relative; margin-bottom: 20px; border-radius: 8px; overflow: hidden; background: rgba(15, 8, 32, 0.6); border: 1px solid rgba(255,255,255,0.1); backdrop-filter: blur(10px); }\n.code-header { display: flex; justify-content: space-between; align-items: center; padding: 8px 15px; background: rgba(0,0,0,0.3); font-family: 'JetBrains Mono', monospace; font-size: 0.85rem; color: #8a7da5; border-bottom: 1px solid rgba(255,255,255,0.05); }\n.copy-btn { background: none; border: none; color: #b8aece; cursor: pointer; transition: color 0.2s; display: flex; align-items: center; gap: 5px; font-size: 0.85rem; }\n.copy-btn:hover { color: #fff; }\n.code-wrapper pre { padding: 15px; overflow-x: auto; font-family: 'JetBrains Mono', monospace; font-size: 0.9rem; color: #e0d8f0; margin: 0; tab-size: 4; }\ncode { font-family: 'JetBrains Mono', monospace; background: rgba(255,255,255,0.1); padding: 2px 6px; border-radius: 4px; font-size: 0.9em; color: #ffaa77; }\n\n.wiki-table-wrapper { overflow-x: auto; margin-bottom: 20px; border-r
<truncated 9384 bytes>
`,

  sushimarket: `
"<!DOCTYPE html>\n<html lang=\"vi\">\n<head>\n<meta charset=\"UTF-8\">\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n<title>SushiMarket Wiki - SushiGangs</title>\n<link href=\"https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:wght@400;600;800&family=JetBrains+Mono&display=swap\" rel=\"stylesheet\">\n<link rel=\"stylesheet\" href=\"style.css\">\n<style>\n.wiki-main { padding: 100px 20px 40px; max-width: 900px; margin: 0 auto; width: 100%; color: #b8aece; line-height: 1.6; }\n.wiki-main h1 { font-size: 2.5rem; color: #fff; margin-bottom: 10px; }\n.wiki-main h2 { font-size: 1.8rem; color: #fff; margin-top: 40px; margin-bottom: 15px; padding-bottom: 10px; border-bottom: 1px solid rgba(255,255,255,0.1); }\n.wiki-main h3 { font-size: 1.3rem; color: #ff77aa; margin-top: 20px; margin-bottom: 10px; }\n.wiki-main p { margin-bottom: 15px; }\n.wiki-main ul, .wiki-main ol { margin-bottom: 15px; padding-left: 20px; }\n.wiki-main li { margin-bottom: 8px; }\n\n.code-wrapper { position: relative; margin-bottom: 20px; border-radius: 8px; overflow: hidden; background: rgba(15, 8, 32, 0.6); border: 1px solid rgba(255,255,255,0.1); backdrop-filter: blur(10px); }\n.code-header { display: flex; justify-content: space-between; align-items: center; padding: 8px 15px; background: rgba(0,0,0,0.3); font-family: 'JetBrains Mono', monospace; font-size: 0.85rem; color: #8a7da5; border-bottom: 1px solid rgba(255,255,255,0.05); }\n.copy-btn { background: none; border: none; color: #b8aece; cursor: pointer; transition: color 0.2s; display: flex; align-items: center; gap: 5px; font-size: 0.85rem; }\n.copy-btn:hover { color: #fff; }\n.code-wrapper pre { padding: 15px; overflow-x: auto; font-family: 'JetBrains Mono', monospace; font-size: 0.9rem; color: #e0d8f0; margin: 0; tab-size: 4; }\ncode { font-family: 'JetBrains Mono', monospace; background: rgba(255,255,255,0.1); padding: 2px 6px; border-radius: 4px; font-size: 0.9em; color: #ffaa77; }\n\n.wiki-table-wrapper { overflow-x: auto; margin-bottom: 20px; border-ra
<truncated 9186 bytes>
`,

  sushitags: `
"<!DOCTYPE html>\n<html lang=\"vi\">\n<head>\n<meta charset=\"UTF-8\">\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n<title>SushiTags Wiki - SushiGangs</title>\n<link href=\"https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:wght@400;600;800&family=JetBrains+Mono&display=swap\" rel=\"stylesheet\">\n<link rel=\"stylesheet\" href=\"style.css\">\n<style>\n.wiki-main { padding: 100px 20px 40px; max-width: 900px; margin: 0 auto; width: 100%; color: #b8aece; line-height: 1.6; }\n.wiki-main h1 { font-size: 2.5rem; color: #fff; margin-bottom: 10px; }\n.wiki-main h2 { font-size: 1.8rem; color: #fff; margin-top: 40px; margin-bottom: 15px; padding-bottom: 10px; border-bottom: 1px solid rgba(255,255,255,0.1); }\n.wiki-main h3 { font-size: 1.3rem; color: #ff77aa; margin-top: 20px; margin-bottom: 10px; }\n.wiki-main p { margin-bottom: 15px; }\n.wiki-main ul, .wiki-main ol { margin-bottom: 15px; padding-left: 20px; }\n.wiki-main li { margin-bottom: 8px; }\n\n.code-wrapper { position: relative; margin-bottom: 20px; border-radius: 8px; overflow: hidden; background: rgba(15, 8, 32, 0.6); border: 1px solid rgba(255,255,255,0.1); backdrop-filter: blur(10px); }\n.code-header { display: flex; justify-content: space-between; align-items: center; padding: 8px 15px; background: rgba(0,0,0,0.3); font-family: 'JetBrains Mono', monospace; font-size: 0.85rem; color: #8a7da5; border-bottom: 1px solid rgba(255,255,255,0.05); }\n.copy-btn { background: none; border: none; color: #b8aece; cursor: pointer; transition: color 0.2s; display: flex; align-items: center; gap: 5px; font-size: 0.85rem; }\n.copy-btn:hover { color: #fff; }\n.code-wrapper pre { padding: 15px; overflow-x: auto; font-family: 'JetBrains Mono', monospace; font-size: 0.9rem; color: #e0d8f0; margin: 0; tab-size: 4; }\ncode { font-family: 'JetBrains Mono', monospace; background: rgba(255,255,255,0.1); padding: 2px 6px; border-radius: 4px; font-size: 0.9em; color: #ffaa77; }\n\n.wiki-table-wrapper { overflow-x: auto; margin-bottom: 20px; border-radi
<truncated 8350 bytes>
`,

};
